<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$aMenuLinks = Array(
	Array(
		"Компания", 
		"http://betterstroy.ru/company/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Новости", 
		"http://betterstroy.ru/news/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Продукция", 
		"http://betterstroy.ru/products/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Услуги", 
		"http://betterstroy.ru/services/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Контакты", 
		"http://betterstroy.ru/contacts/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>